### PR TITLE
Explicitly specify command for k8s spec

### PR DESCRIPTION
**Pull request by nemani**

### CODE REVIEW

**Comment by jsravn** [comment]
LGTM.

**Comment by bmm-alc** [comment]
Hello,

that would be useful for people tracking the project  to explain rather why you trying to do rather what you did in the commit. I don't get why you use a script called `launch_within_docker.sh` a container in k8s.

**Comment by nemani** [comment]
We use an bash script as entrypoint to our containers. This script is called `launch_within_docker.sh`. 
Due to a change in [containerd.io-1.6.18](https://github.com/containerd/containerd/releases/tag/v1.6.18) & [go 1.19.6](https://github.com/golang/go/issues/43724) we need to use absolute path to the script. 
This should not be a requirement once for new patches released by us. 
But in the meantime we are changing the template to workaround this. 
This matches with all the other templates we provide.

**Comment by bmm-alc** [comment]
Thanks for the reply.
It's appreciated.

Have a nice day.

**Pull request closed without merging**
